class Strings:
    # --- APP INFO ---
    APP_TITLE = "Dex Dictate v3 - Starsilk Expansion"
    APP_LOGO = "DEX DICTATE"
    
    # --- WINDOW TITLES ---
    TITLE_HISTORY = "Transcription History"
    TITLE_COMMANDS = "Available Commands"
    TITLE_SETTINGS = "Settings"
    
    # --- MODES ---
    MODE_WAKE = "WAKE WORD"
    MODE_MANUAL = "MANUAL"
    MODE_FOCUS = "FOCUS (VAD)"
    
    # --- BUTTONS ---
    BTN_HISTORY = "HISTORY"
    BTN_COMMANDS = "COMMANDS"
    BTN_TOOLBAR = "TOOLBAR"
    BTN_CLIPBOARD = "CLIPBOARD"
    BTN_SETTINGS = "SETTINGS"
    BTN_STOP_DAEMON = "STOP DAEMON"
    BTN_START_DAEMON = "START DAEMON"
    BTN_SEND_TEST = "SEND TO ENGINE"
    BTN_CLOSE_DRAWER = "CLOSE DRAWER"
    BTN_ADD_CMD = "ADD COMMAND"
    BTN_REMOVE_CMD = "REMOVE SELECTED"
    BTN_EXPORT_CFG = "EXPORT CONFIG"
    BTN_IMPORT_CFG = "IMPORT CONFIG"
    BTN_HELP = "HELP"
    BTN_CLEAR_HIST = "CLEAR HISTORY"
    BTN_CAPTURE = "Capture Now"
    BTN_COPY = "Copy"
    BTN_SAVE_PINNED = "Save Pinned"
    
    # --- STATUS ---
    STATUS_IDLE = "IDLE"
    STATUS_RECORDING = "RECORDING"
    STATUS_OFFLINE = "OFFLINE"
    STATUS_CONNECTED = "CONNECTED"
    STATUS_THINKING = "THINKING"
    STATUS_WRITING = "WRITING"
    
    # --- HEADERS ---
    HDR_OP_MODE = "OPERATION MODE"
    HDR_SENSITIVITY = "SENSITIVITY"
    HDR_MANUAL_HK = "MANUAL HOTKEYS"
    HDR_SUBSYSTEMS = "SUBSYSTEMS"
    HDR_DAEMON_CTRL = "DAEMON CONTROL"
    HDR_TEST_INPUT = "TEST INPUT"
    HDR_SYS_LOG = "SYSTEM LOG"
    HDR_INSPECTOR = "INSPECTOR (TELEMETRY)"
    HDR_GEN_SETTINGS = "GENERAL"
    HDR_THEME_ACCENT = "THEME ACCENT"
    HDR_BG_THEME = "BACKGROUND THEME"
    HDR_AUDIO_INPUT = "AUDIO INPUT"
    HDR_CONFIG = "CONFIGURATION"
    HDR_BEHAVIOR = "BEHAVIOR"
    
    # --- TOOLTIPS ---
    TT_HELP = "Help & FAQ"
    TT_HISTORY = "View Transcription History"
    TT_COMMANDS = "Manage Voice Commands"
    TT_TOOLBAR = "Toggle Desktop Toolbar"
    TT_CLIPBOARD = "View Clipboard History"
    TT_SETTINGS = "Configure Application"
    TT_DAEMON = "Start/Stop Background Service"
    TT_SEND_TEST = "Simulate Voice Input"
    
    # --- ACCESSIBILITY ---
    A11Y_LOGO = "Dex Dictate Logo"
    A11Y_MODE_WAKE = "Wake Word Mode"
    A11Y_DESC_WAKE = "Activates voice activation mode using Porcupine."
    A11Y_MODE_MANUAL = "Manual Mode"
    A11Y_DESC_MANUAL = "Activates push-to-talk mode."
    A11Y_MODE_FOCUS = "Focus Mode"
    A11Y_DESC_FOCUS = "Activates voice activity detection mode."
    A11Y_VISUALIZER = "Audio Visualizer"
    A11Y_STATUS_IDLE = "System Status: Idle"
    A11Y_STATUS_PREFIX = "System Status: "
    A11Y_HELP = "Help and FAQ"
    A11Y_SENSITIVITY = "Microphone Sensitivity"
    A11Y_DESC_SENSITIVITY = "Adjusts the sensitivity threshold for voice activity detection."
    A11Y_OPEN_HIST = "Open History Panel"
    A11Y_OPEN_CMD = "Open Commands Panel"
    A11Y_TOGGLE_BAR = "Toggle Desktop Toolbar"
    A11Y_OPEN_CLIP = "Open Clipboard Panel"
    A11Y_OPEN_SETTINGS = "Open Settings Panel"
    A11Y_TOGGLE_DAEMON = "Toggle Daemon Service"
    A11Y_TEST_INPUT = "Test Input Field"
    A11Y_SEND_TEST = "Send Test Input"
    A11Y_LOG_OUT = "System Log Output"
    A11Y_CLEAR_HIST = "Clear History"
    A11Y_CLOSE_CLIP = "Close Clipboard Drawer"
    A11Y_CAP_CLIP = "Capture Clipboard Now"
    A11Y_COPY_LAST = "Copy Last Captured Clipboard"
    A11Y_SAVE_PIN = "Save Pinned Note"
    A11Y_COPY_PIN = "Copy Pinned Note"
    A11Y_CLOSE_CMD = "Close Command Drawer"
    A11Y_NEW_TRIG = "New Command Trigger"
    A11Y_NEW_ACT = "New Command Action"
    A11Y_ADD_CMD = "Add New Command"
    A11Y_SEARCH_CMD = "Search Commands"
    A11Y_REM_CMD = "Remove Selected Command"
    A11Y_CLOSE_SET = "Close Settings Drawer"
    A11Y_THEME_ACCENT = "Theme Accent: "
    A11Y_BG_THEME = "Background Theme Selector"
    A11Y_AUDIO_IN = "Audio Input Selector"
    A11Y_REC_START = "Start Recording Hotkey"
    A11Y_REC_STOP = "Stop Recording Hotkey"
    A11Y_EXPORT = "Export Configuration"
    A11Y_IMPORT = "Import Configuration"
    A11Y_TRAY = "Minimize to Tray Checkbox"
    
    # --- LOGS / TOASTS ---
    LOG_MODE_SET = "Mode set to {}"
    LOG_INJECTING = "Injecting: {}"
    LOG_THEME = "Theme applied: {} | {}"
    TOAST_EXPORT = "Config Exported to {}"
    TOAST_IMPORT = "Config Imported! Restarting..."
    TOAST_CMD_ADDED = "Command Added!"
    TOAST_CMD_REMOVED = "Command Removed!"
    TOAST_REINJECT = "Re-injecting Text..."
